### ISSUE TITLE
[1.3-modules-beta.8] can't use tsumina:meteor-systemjs

### ISSUE THREAD

**Issue by stphdenis** [TsumiNa/meteor-systemjs#3]
With a fresh meteor app :

```
meteor --release METEOR@1.3-modules-beta.8 create tstV3_SystemJS
cd tstV3_SystemJS
meteor remove blaze-html-templates
meteor add tsumina:meteor-systemjs
meteor
```

on the server, we get this error :

```
=> Started proxy.
=> Started MongoDB.
Message: Using Systemjs Loader...
Message: Using Aurelia Framework...
=> Exited with code: 8
W20160208-12:05:35.664(0)? (STDERR)
W20160208-12:05:35.665(0)? (STDERR) C:\Users\...\AppData\Local\.meteor\packages\meteor-tool\1.1.13-modules.8\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20160208-12:05:35.665(0)? (STDERR)                                             throw(ex);
W20160208-12:05:35.666(0)? (STDERR)                                                   ^
W20160208-12:05:35.666(0)? (STDERR) Error: Cannot find module 'babel-runtime/helpers/typeof'
W20160208-12:05:35.666(0)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20160208-12:05:35.666(0)? (STDERR)     at Function.Module._load (module.js:280:25)
W20160208-12:05:35.666(0)? (STDERR)     at Module.require (module.js:364:17)
W20160208-12:05:35.667(0)? (STDERR)     at require (module.js:380:17)
W20160208-12:05:35.667(0)? (STDERR)     at Npm.require (C:\Users\...\meteor\tstV3_SystemJS\.meteor\local\build\programs\server\boot.js:150:18)
W20160208-12:05:35.667(0)? (STDERR)     at C:\Users\...\meteor\tstV3_SystemJS\.meteor\local\build\programs\server\packages\tsumina_meteor-systemjs.js:37:16
W20160208-12:05:35.667(0)? (STDERR)     at C:\Users\...\meteor\tstV3_SystemJS\.meteor\local\build\programs\server\packages\tsumina_meteor-systemjs.js:5824:3
W20160208-12:05:35.668(0)? (STDERR)     at C:\Users\...\meteor\tstV3_SystemJS\.meteor\local\build\programs\server\boot.js:242:10
W20160208-12:05:35.668(0)? (STDERR)     at Array.forEach (native)
W20160208-12:05:35.668(0)? (STDERR)     at Function._.each._.forEach (C:\Users\...\AppData\Local\.meteor\packages\meteor-tool\1.1.13-modules.8\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
```

As we can see, it seems to be a depedency problem from `system-polyfills.src.js` : `tsumina_meteor-systemjs.js:37:16`

``` javascript
var _typeof2 = require('babel-runtime/helpers/typeof');
```

**Comment by stphdenis** [comment]
There's an issue : https://phabricator.babeljs.io/T6644 that has been resolved in part with the version : babel-runtime@6.3.19

**Comment by plasmalance** [comment]
@stphdenis How did you fix this?

**Comment by stphdenis** [comment]
A have not still fixed it totaly, It stays the html templates static loading.

To begin, I have just loaded Aurelia with Systemjs with npm, without your packages.

```
npm i --save systemjs
npm i --save aurelia-bootstrapper
```

Loader of meteor nmp modules in Systemjs : meteor-plugin.js

``` ecmascript
function toCamelCase(str) {
  const t = str.replace(/(?:^|\.?)(_.-)/g, (x, y) => y.toUpperCase()[1]);
  return t.charAt(0).toUpperCase() + t.substr(1);
}

exports.instantiate = function instantiate(load) {
  const name = load.name.substr(this.baseURL.length);
  let module;
  try {
    module = require(`/${name}`);
  } catch (e) {
    const names = name.split('/');
    module = require(names[0]);
    for (let i = 1; i < names.length; i++) {
      const camelName = toCamelCase(names[i]);
      module = module[camelName];
    }
  }
  return module;
};
```

Initialization of Systemjs : init-systemjs.js

``` ecmascript
import 'systemjs';

System.paths['meteor-plugin'] = '/systemjs/plugin/meteor-plugin.js';
System._loader.modules['http://localhost:3000/systemjs/plugin/meteor-plugin.js'] = {};
System._loader.modules['http://localhost:3000/systemjs/plugin/meteor-plugin.js'].module = require('./meteor-plugin');

System.config({
  baseURL: '/',
  map: {
    'meteor-plugin': '/systemjs/plugin/meteor-plugin.js',
  },
  meta: {
    '/*': {
      loader: 'meteor-plugin',
    },
  },
});
```

Initialization of Aurelia : main.js

```
import 'aurelia-polyfills';
import { LogManager } from 'aurelia-framework';
import { ConsoleAppender } from 'aurelia-logging-console';
import 'aurelia-templating-binding';
import 'aurelia-templating-resources';
import 'aurelia-history-browser';
import 'aurelia-templating-router';
import 'aurelia-bootstrapper';
import 'aurelia-loader-default';
import 'aurelia-framework';

LogManager.addAppender(new ConsoleAppender());
LogManager.setLevel(LogManager.logLevel.debug);

export function configure(aurelia) {
  aurelia.use
    .defaultBindingLanguage()
    .defaultResources()
    .history()
    .router()
    .eventAggregator();

  aurelia.start().then(() => aurelia.setRoot('./client/app/app', document.body));
}
```

**Comment by stphdenis** [comment]
I have used a new way to bootstrap with meteor.
I have made a native meteor loader : `aurelia-bootstrapper-meteor` and `aurelia-loader-meteor` based on `aurelia-bootstrapper-webpack` and `aurelia-loader-webpack` and all is fine !!! Beside, we need a meteor package to load the template files.

**Comment by stphdenis** [comment]
The meteor package is : `sdenis:static-raw-html` to be able to have <template> as static html.
